name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  mcstas:
    runs-on: ubuntu-latest
    container: mccode/mcstas-3.4
    steps:
      # - name: checkout repository
        # uses: actions/checkout@v4

      - name: run mcstas
        run: mcstas --version
